---
# SPDX-License-Identifier: MPL-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Chore"
    open-pull-requests-limit: 15
    cooldown:
      default-days: 7
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Chore"
    open-pull-requests-limit: 15
    cooldown:
      default-days: 7
    exclude-paths:
      - "LICENSES/**"
    ignore:
      - dependency-name: "meson"
      - dependency-name: "meson-python"
